#!/bin/bash
# NOTE: This must be run with bash and not sh.

# This script creates a tgz backup of the whole project.

#COPY_TO=~/host/Dropbox/Backups/ufo-c
COPY_TO=~/host

rm -f list-of-files
find src -name '*.c'          >> list-of-files
find src -name '*.h'          >> list-of-files
find ffi -name '*.c'          >> list-of-files
find ffi -name '*.txt'        >> list-of-files
find test -name '*.c'         >> list-of-files
find test -name '*.h'         >> list-of-files
find test -name '*.txt'       >> list-of-files
find doc-local -name '*.txt'  >> list-of-files
ls examples/*.ufo             >> list-of-files
ls script/*                   >> list-of-files
ls LICENSE                    >> list-of-files
ls Makefile                   >> list-of-files
ls pmake.py                   >> list-of-files
ls README.md                  >> list-of-files
ls .gitignore                 >> list-of-files

DESC="-$1"
if [ "-$1-" == "--" ]; then
  DESC=""
fi
NAME=`date +'%y%m%d-%H%M'${DESC}`.tgz
echo ${NAME}
tar --exclude=*~ -zcf .backups/${NAME} -T list-of-files

if [ -d "$COPY_TO" ]
then
    cp .backups/${NAME} $COPY_TO
else
    echo "Not copying to $COPY_TO"
fi
